#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include QMK_KEYBOARD_CONFIG_H

#define TAPPING_TERM 175
#define TAPPING_TOGGLE 3
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#define MOUSEKEY_INTERVAL 25
#define MOUSEKEY_MAX_SPEED 8

#endif