#include QMK_KEYBOARD_H

#define _QWERTY 0
#define _COLEMAK 1
#define _DVORAK 2
#define _NAV 3
#define _NAV2 4
#define _FN 5
#define _ADJUST 16

#define TAPPING_TOGGLE 2


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [_QWERTY] = LAYOUT_ortho_4x4(
    KC TAB,  KC_Q, KC_W, KC_E, KC_R, KC_T,                            KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPACE,
    LSFT_T(KC_GRAVE), LSFT_T(KC_A), KS_S, KC_D, KC_F, KC_G,           KC_H, KC_J, KC_K, KC_L, RSFT_T(KC_SCLN), RSFT_T(KC_QUOTE),
    LCTL_T(KC_MINUS), LGUI_T(KC_Z), LALT_T(KC_X), KC_C, KC_V, KC_B,   KC_N, KC_M, KC_COMMA, RALT_T(KC_DOT), RGUI_T(KC_SLSH), RCTL_T(KC_EQUAL),
    KC_LCTL, KC_LGUI, KC_LALT, KC_DEL, TT(_NAV), KC_SPACE,            KC_ENTER, TT(_FN), KC_BSPACE, KC_RALT, KC_RGUI, KC_RCTL
  ),

  [_DVORAK] = LAYOUT_ortho_4x4(
    KC TAB, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y,                      KC_F, KC_G, KC_C, KC_R, KC_L, KC_BSPC,
    LSFT_T(KC_GRAVE), LSFT_T(KC_A), KC_O, KC_E, KC_U, KC_I,            KC_D, KC_H, KC_T, KC_N, RSFT_T(KC_S), RSFT_T(KC_SLSH),
    LCTL_T(KC_MINUS), LGUI_T(KC_SCLN), LALT_T(KC_Q), KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, RALT_T(KC_V), RGUI_T(KC_Z), RCTL_T(KC_ENT),
    KC_LCTL, KC_LGUI, KC_LALT, KC_DEL, TT(_NAV), KC_SPACE,            KC_ENTER, TT(_FN), KC_BSPACE, KC_RALT, KC_RGUI, KC_RCTL
  ),

  [_COLEMAK] = LAYOUT_ortho_4x4(
    KC TAB, KC_Q, KC_W, KC_F, KC_P, KC_G,                             KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSPC,
    LSFT_T(KC_GRAVE), LSFT_T(KC_A), KC_R, KC_S, KC_T, KC_D,           KC_H, KC_N, KC_E, KC_I, RSFT_T(KC_O), RSFT_T(KC_QUOT),
    LCTL_T(KC_MINUS), LGUI_T(KC_Z), LALT_T(KC_X), KC_C, KC_V, KC_B,   KC_K, KC_M, RALT_T(KC_COMMA), RGUI_T(KC_DOT), RCTL_T(KC_ENTER),
    KC_LCTL, KC_LGUI, KC_LALT, KC_DEL, TT(_NAV), KC_SPACE,            KC_ENTER, TT(_FN), KC_BSPACE, KC_RALT, KC_RGUI, KC_RCTL
  ),

  [_NAV] = LAYOUT_ortho_4x4(
    KC_ESC, KC_TAB, KC_HOME, KC_UP, KC_END, KC_PGUP,             KC_WH_U, KC_BTN_1, KC_MS_U, KC_BTN_2, KC_DEL, KC_BSPC,
    KC_VOLU, KC_LSFT, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGDN,       KC_WH_D, KC_MS_L, KC_MS_D, KC_MS_R, KC_RSFT, KC_ENT,
    KC_VOLD, KC_MUTE, C(KC_LEFT), KC_TRNS, C(KC_RIGHT), KC_TRNS, KC_ACL0, KC_ACL1, KC_ACL2, S(KC_RALT), S(KC_RGUI), S(KC_RCTL),
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,        KC_TRNS, TT(_ADJUST), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [_NAV2] = LAYOUT_ortho_4x4(
    KC_ESC, KC_TAB, KC_BTN_2, KC_MS_U, KC_BTN_1, KC_WH_U,        KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_DEL, KC_BSPC,
    KC_VOLU, KC_LSFT, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D,        KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, RSFT_T(KC_PSCREEN), KC_ENT,
    KC_VOLD, KC_MUTE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,        KC_ACL0, KC_ACL1, KC_ACL2, S(KC_RALT), S(KC_RGUI), S(KC_RCTL),
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,        KC_TRNS, TT(_ADJUST), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [_FN] = LAYOUT_ortho_4x4(
    KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,                  KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
    KC_TRNS, LSFT_T(KC_1), KC_2, KC_3, KC_4, KC_5,              KC_6, KC_7, KC_8, KC_9, RSFT_T(KC_0), RSFT_T(KC_PSCREEN)
    KC_TRNS, KC_TRNS, S(KC_COMM), KC_LBRC, S(KC_LBRC), S(KC_9), S(KC_0), S(KC_RBRC), KC_RBRC, S(KC_DOT), KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TT(_ADJUST), KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [_ADJUST] = LAYOUT_ortho_4x4(
    KC_TRNS, DF(_QWERTY), DF(_DVORAK), DF(_COLEMAK), KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_CAPS, S(KC_1), S(KC_2), S(KC_3), S(KC_4), S(KC_5),               S(KC_6), S(KC_7), S(KC_8), S(KC_9), S(KC_0), KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,               KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,               KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  )

};
